### ISSUE TITLE
Dependency Types

### ISSUE THREAD

**Issue by victoraugustolls** [microsoft/opentelemetry-azure-monitor-python#10]
Proposal:

- Use OpenTelemetry specs to make it possible to determine some of the dependency types that ApplicationInsights accept.
- Be able to force a dependency type to include the ones that are out of OpenTelemetry specs.

**Comment by victoraugustolls** [comment]
I tried to add a label to the issue, but I don't seem to be able to!

**Comment by lzchen** [comment]
@victoraugustolls 
Are you referring to putting the telemetry types of Application Insights (`MetricData`, `RemoteDependencyData`, etc) into OpenTelemetry specs?

**Comment by victoraugustolls** [comment]
Sorry for the delay @lzchen! I meant using the specs listed [here](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/data-http.md) and [here](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/data-database.md) so we can make the right dependency type appear in the Application Map and etc...

**Comment by lmolkova** [comment]
`component` attribute should be used for it. 

There is also a special proposal for Azure SDKs to stamp their type in `az.namespace` attribute as `component` is not good enough gor Azure Monitor UX (describles only protocol, but not the service it calls). But this proposal is not yet implemented. I'll keep you posted

**Comment by victoraugustolls** [comment]
Hi!

Do we have any news of this proposal @lmolkova ?

Thanks in advance!

**Comment by lzchen** [comment]
@victoraugustolls 
I don't believe `component` attribute is being used/implemented across all languages/instrumentations.

Currently, Azure exporters will be using their own mechanism to detect dependency type. Issue here: https://github.com/microsoft/opentelemetry-azure-monitor-python/issues/128

**Comment by victoraugustolls** [comment]
Thanks for the info @lzchen ! I think this can be closed and tracked in #128!
