### ISSUE TITLE
Improve request/dependencies metrics availability (Perf Counter/Live Metrics)

### ISSUE THREAD

**Issue by hectorhdzg** [microsoft/opentelemetry-azure-monitor-python#106]
Currently we rely on monkey patching to be able to retrieve perf counter and live metrics regarding dependencies and requests, this could be improved by adding support for other popular libraries or to push for some capabilities in OT SDKs to achieve this.

**Comment by lzchen** [comment]
Request/dependencies will be done through https://github.com/microsoft/opentelemetry-azure-monitor-python/issues/123
