### ISSUE TITLE
Azure Functions

### ISSUE THREAD

**Issue by victoraugustolls** [microsoft/opentelemetry-azure-monitor-python#107]
Hi!

I was wondering, what would be the best way to integrate OpenTelemetry (and OpenCensus) to an Python Azure Functions.

In a web app we start the exporter on startup, but what about an AzureFunction? I don't think the best way was to start a new exporter every time a functions starts running, it seems like it would maybe cause memory problems (?), due to the local storage?

Was wondering if someone here has any opinions about this! Thanks!

**Comment by lzchen** [comment]
@victoraugustolls 
We have indeed been looking into how to use our SDKs and integrate them into Azure Functions. This will be part of our "attach" story when we implement python sdks directly into Azure Function's architecture. However, for now we will expect users to manually instrument their applications directly.

Besides from the issues that you outlined above, there are also issues of functions exiting too quickly before the SDK has a chance to even send telemetry as well. These problems are currently being discussed. Any other scenarios would be greatly appreciated as well!

**Comment by victoraugustolls** [comment]
@lzchen thanks for the answer!

Is there a way for me to follow does this discussions, or are they happening inside Microsoft?
Also, is any way for me to help you guys?

**Comment by victoraugustolls** [comment]
> This will be part of our "attach" story when we implement python sdks directly into Azure Function's architecture.

Does this means that the Azure Functions Python host would start the trace with opentelemetry python sdk, something like this, and we would only need to start the spans inside the function?

**Comment by victoraugustolls** [comment]
Missclicked, sorry

**Comment by lzchen** [comment]
> Is there a way for me to follow does this discussions, or are they happening inside Microsoft?
> Also, is any way for me to help you guys?

I believe these discussions are happening inside Microsoft but I will keep you updated.

>Does this means that the Azure Functions Python host would start the trace with opentelemetry python sdk, something like 
> this, and we would only need to start the spans inside the function?

Yes. Azure Functions will automatically instrument the function with the SDK, and then you create spans manually inside the function.

**Comment by lzchen** [comment]
Closing. Will be reopened when azure functions support for attach is implemented.
