### ISSUE TITLE
Using ValueEncoder

### ISSUE THREAD

**Issue by hungapl** [microsoft/opentelemetry-azure-monitor-python#108]
Hi I have tried to use ValueEncoder to capture some job latency from my Python code, but it seems the value shared to the Azure Monitor is the count instead of value, is that the expected behaviour?

This is the code I use to test

`    
   metrics.set_meter_provider(MeterProvider())

    meter = metrics.get_meter(__name__)

    exporter = AzureMonitorMetricsExporter(
        connection_string='InstrumentationKey=' + args.instrumentation_key
    )

    controller = PushController(meter, exporter, 5)
    job_duration = meter.create_metric(
        name="job_duration",
        description="job_duration",
        unit="1",
        value_type=int,
        metric_type=ValueRecorder,
        label_keys=("environment", "task")
    )

    testing_labels = {"environment": "testing", "task":"preprocess"}
    job_duration.record(25, testing_labels)`
`

In Application Insights Log Analytics, the 'value' is recorded as 1 instead of 25

This is what I found in the AzureMonitorMetricsExporter class:

`
        if isinstance(metric, ValueObserver):
            # mmscl
            value = metric_record.aggregator.checkpoint.last
        elif isinstance(metric, ValueRecorder):
            # mmsc
            value = metric_record.aggregator.checkpoint.count
`

**Comment by lzchen** [comment]
`ValueRecorder` uses the [MinMaxSumCountAggregator](https://github.com/open-telemetry/opentelemetry-python/blob/master/opentelemetry-sdk/src/opentelemetry/sdk/metrics/export/aggregate.py#L82) which does not have well defined behaviour in AzureMonitor. As it is still in beta, we are defaulting the exported value to be the count for now. In the future, we expect the exporter to export a `summary` value to AzureMonitor (all four of min,max,sum and count).

**Comment by hungapl** [comment]
Thanks for the quick reply, that explains why the code is doing that.
