### ISSUE TITLE
Upload new version of package to pypi.org

### ISSUE THREAD

**Issue by adamko147** [microsoft/opentelemetry-azure-monitor-python#118]
Hi, since https://github.com/microsoft/opentelemetry-azure-monitor-python/pull/117 is already merged, could you please release new version of the package into pypi.org so I can pull it and use with latest OT 0.13 packages?
Thanks a lot!

**Comment by lzchen** [comment]
Will be doing a release later this week.

**Comment by adamko147** [comment]
@lzchen thank you very much.
apart from that, aren’t you aware of the opentelemtry azure monitor exporter for go? Thanks!

**Comment by lzchen** [comment]
@adamko147 
I do not believe that exists yet.

**Comment by lzchen** [comment]
https://github.com/microsoft/opentelemetry-azure-monitor-python/releases/tag/v0.5.0
