### ISSUE TITLE
Documenting TODOs

### ISSUE THREAD

**Issue by SinfulPhantom** [microsoft/opentelemetry-azure-monitor-python#12]
There are several TODOs scattered around the code base such as:
https://github.com/microsoft/opentelemetry-exporters-python/blob/8aac369664eafa82e8ed77d7d69067ef8cebf9a3/azure_monitor/src/azure_monitor/trace.py#L125

Could there be a string detailing what needs to be done after the TODO or can issues be made so that these can be taken care of?

**Comment by lzchen** [comment]
Yes this is a good suggestion. @reyang can you help here?

**Comment by reyang** [comment]
@lzchen, most likely not due to other priorities.

**Comment by lzchen** [comment]
Fixed with [#23]
