### ISSUE TITLE
Support for python logging

### ISSUE THREAD

**Issue by tcsatheesh** [microsoft/opentelemetry-azure-monitor-python#131]
Hi,

I am working inside a Databricks cluster and using opentelemetry and azure-monitor. I've done the initial setup and all span items are being published into App Insights. However I am unable to publish logging.info and logging.error messages into App Insights.

My logging is setup with the configuration below

 
    logger = logging.getLogger(__name__) 
    formatter = logging.Formatter(
    '%(asctime)s - %(name)s - %(levelname)s - %(message)s')
    stream_handler = logging.StreamHandler()
    stream_handler.setLevel(logging.DEBUG)
    stream_handler.setFormatter(formatter)
    logger.addHandler(stream_handler)
    logger.setLevel(logging.DEBUG)`

Any logger.info or logger.error messages are printed to the notebook cell results window.
Its not clear how I can publish these messages to App Insights traces and exceptions.

My opentelemetry is set up as follows

    trace.set_tracer_provider(TracerProvider())
    # trace.get_tracer_provider().add_span_processor(SimpleExportSpanProcessor(ConsoleSpanExporter()))
    tracer = trace.get_tracer(__name__)

    instrumentation_key = dbutils.secrets.get(scope="<scope>",key="appinsights-instrumentation-key")
   
    # SpanExporter receives the spans and send them to the target location
    span_exporter = AzureMonitorSpanExporter(
    instrumentation_key=instrumentation_key)
    span_processor = BatchExportSpanProcessor(span_exporter)
    trace.get_tracer_provider().add_span_processor(span_processor)

    # Set global MeterProvider before recording
    metrics.set_meter_provider(MeterProvider())
    meter = metrics.get_meter(__name__, True)
    metrics_exporter = AzureMonitorMetricsExporter(
      instrumentation_key=instrumentation_key)
    controller = PushController(meter, metrics_exporter, 5)
    processed_rows_counter = meter.create_metric(name="processed_rows",
                                             description="number of rows",
                                             unit="1",
                                             value_type=int,
                                             metric_type=Counter)

Can someone please advice if what I am asking is supported in azure-monitor for opentelemetry? If so what would I need to do to setup logging to send traces and exceptions to App Insights?

**Comment by lzchen** [comment]
Logging is not supported currently. We should have a log exporter by the end of this year.

**Comment by ctaggart** [comment]
> Can someone please advice if what I am asking is supported in azure-monitor for opentelemetry? If so what would I need to do to setup logging to send traces and exceptions to App Insights?

@lzchen Will it be possible to "setup logging to send traces and exceptions to App Insights", not Log Analytics?

**Comment by lzchen** [comment]
@ctaggart

> Will it be possible to "setup logging to send traces and exceptions to App Insights"

Yes this is what the proposed log exporter will do, similarly to [Opencensus](https://github.com/census-instrumentation/opencensus-python/blob/master/contrib/opencensus-ext-azure/opencensus/ext/azure/log_exporter/__init__.py#L152) log exporter to Azure monitor.
