### ISSUE TITLE
after quickly adding metrics, too many arriving in azure

### ISSUE THREAD

**Issue by kenoc1** [microsoft/opentelemetry-azure-monitor-python#133]
I open this ticket because I was asked for it in a comment from my stackoverflow question https://stackoverflow.com/questions/64899311/opentelemetry-add-metrics-explicitly-azure-monitor-opentelemetry

i want to track the use of certain ids in ms azure monitor (application insights). I'm doing this at the moment with the following code excerpt. The problem is that if, for example, eight calls are made in quick succession, the first call is tracked eight times. the second is tracked seven times. the third six times and so on. (look at the picture below) Don't know  if it's my fault or a bug.

```python
from azure_monitor import AzureMonitorMetricsExporter
from opentelemetry import metrics
from opentelemetry.sdk.metrics import Counter, MeterProvider
from opentelemetry.sdk.metrics.export.controller import PushController

metrics.set_meter_provider(MeterProvider())
meter = metrics.get_meter(__name__)
exporter = AzureMonitorMetricsExporter(
    connection_string='InstrumentationKey=<my-key>'
)
controller = PushController(meter, exporter, 10)
request_counter_question = meter.create_metric(
    name="question",
    description="question used",
    unit="1",
    value_type=int,
    metric_type=Counter,
)


def add_question(question_id):
    labels = {"type": "question", "question_id": question_id}
    request_counter_question.add(1, labels)
    print(str(datetime.now()) + " - Done recording metric: question")
    print(question_id)
    controller.shutdown()
```

![image](https://user-images.githubusercontent.com/47333651/99813311-d0c25080-2b47-11eb-96f6-5bc9078496cb.png)

**Comment by lzchen** [comment]
@kenoc1 

How is `add_question()` being called?

**Comment by kenoc1** [comment]
> @kenoc1
> 
> How is `add_question()` being called?

@lzchen 
I iterate a list with a foreach loop

**Comment by lzchen** [comment]
Try removing `controller.shutdown()`

**Comment by kenoc1** [comment]
> Try removing `controller.shutdown()`
@lzchen  tried it, but now got this. There should be only one call per id to be seen here
With the following query i got this:
`
customMetrics 
| where timestamp > ago(10min) 
| where name == "question"
| summarize Count=count() by tostring(customDimensions["question_id"])
`
![image](https://user-images.githubusercontent.com/47333651/100382195-11740b00-301b-11eb-968b-7ab6b5c6fd2d.png)

if i dont stop my application or do a `controller.shutdown` the metrics grows and grows: (few minutes later)
![image](https://user-images.githubusercontent.com/47333651/100382590-f6ee6180-301b-11eb-8296-e5ad8e698a7a.png)

**Comment by lzchen** [comment]
@kenoc1

The default behaviour of the collection of metrics is that they keep the state for each export cycle (cumulatives).
If you want to only export the total values that were recorded but only within individual exports (deltas) then you can set `stateful=false` in your `MeterProvider()`.

```
metrics.set_meter_provider(MeterProvider(stateful=false))
```

Keep in mind though that Opentelemetry is still in beta and these apis could change.

**Comment by kenoc1** [comment]
Thank you very much for helping me @lzchen!! That solved my problem ;)
