### ISSUE TITLE
Incompatible with current version of opentelemetry-instrumentation-django

### ISSUE THREAD

**Issue by oscarhermoso** [microsoft/opentelemetry-azure-monitor-python#134]
Hi all,

I was looking at using this library to connect my Django server hosted on an App Service to Azure Application Insights.

Unfortunately, the opentelemetry-instrumentation-django package installs opentelemetry-api 0.16b1 and opentelemetry-sdk 0.16b1, but the current release of opentelemetry-azure-monitor 0.5b0 requires opentelemetry-sdk==0.13b0, which is incompatible.

I understand from the other issues that you guys are moving this repository and changes are currently frozen, but is there a loose ETA or any advice that I can follow to get insights into my app using OpenTelemetry?

**Comment by oscarhermoso** [comment]
Hope you're enjoying your holidays too :)

**Comment by lzchen** [comment]
@oscarhermoso 

Opentelemetry Azure Monitor Tracing Exporter now lives under the [Azure](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/monitor/azure-opentelemetry-exporter-azuremonitor) repository. Follow the README and you should be able to get telemetry into App Insights.

**Comment by oscarhermoso** [comment]
Hmm, that link 404's for me. Is the new repository publicly accessible yet?

**Comment by lzchen** [comment]
@oscarhermoso 
Sorry, fixed the link.

**Comment by oscarhermoso** [comment]
Thanks @lzchen

Love your work
