### ISSUE TITLE
Make trace exporter asynchronous using worker threads

### ISSUE THREAD

**Issue by lzchen** [microsoft/opentelemetry-azure-monitor-python#19]
Like in OpenCensus:
https://github.com/census-instrumentation/opencensus-python/blob/master/contrib/opencensus-ext-azure/opencensus/ext/azure/trace_exporter/__init__.py

**Comment by hectorhdzg** [comment]
Having some similar as [OT Metrics PushController](https://github.com/open-telemetry/opentelemetry-python/blob/master/opentelemetry-sdk/src/opentelemetry/sdk/metrics/export/controller.py) would be better instead of adding this kind of logic inside this exporter

**Comment by hectorhdzg** [comment]
OpenTelemetry have BatchExportSpanProcessor available for this purpose

https://opentelemetry-python.readthedocs.io/en/stable/sdk/trace.export.html#opentelemetry.sdk.trace.export.BatchExportSpanProcessor
