### ISSUE TITLE
[QUESTION] BaseObject

### ISSUE THREAD

**Issue by victoraugustolls** [microsoft/opentelemetry-azure-monitor-python#26]
Hi!

I was just wondering if there is a practical reason for using the BaseObject in protocol.py as the base for pretty much everything, instead of normal objects (maybe with __slots__ for optimization) instead!

I know open census exporter was built this way, so if the reason was just to reutilize code, I’m glad to open a PR to make a typed and (maybe) optimized version!!

**Comment by lzchen** [comment]
@victoraugustolls 
Yes the OpenTelemetry exporter was essentially a copy/paste from OpenCensus. If you have any ideas on improving this, feel free to propose them here!

**Comment by hectorhdzg** [comment]
Optimized code is merged now
