### ISSUE TITLE
Flush telemetry on application exit + Implement Queue mechanism

### ISSUE THREAD

**Issue by lzchen** [microsoft/opentelemetry-azure-monitor-python#43]
Like in OpenCensus, can use a `Queue` structure for queuing up telemetry to be exported for trace exporter. This will be used for the `atexit` trigger in the exporter to flush telemetry before exiting the application.
https://github.com/census-instrumentation/opencensus-python/blob/master/contrib/opencensus-ext-azure/opencensus/ext/azure/trace_exporter/__init__.py#L161

For metrics, all the currently aggregated metrics can be collected and flushed at once when the application is closed.

https://github.com/census-instrumentation/opencensus-python/blob/master/contrib/opencensus-ext-azure/opencensus/ext/azure/meatrics_exporter/__init__.py#L145

**Comment by hectorhdzg** [comment]
OT BatchExportSpanProcessor will take care of sending all queued telemetry when the App is closed, we don't need to implement this in here
