### ISSUE TITLE
Latest version  0.3b0 raises an error that Envelope is not JSON serializable

### ISSUE THREAD

**Issue by tcsatheesh** [microsoft/opentelemetry-azure-monitor-python#91]
When trying the sample from https://github.com/microsoft/opentelemetry-azure-monitor-python/blob/master/azure_monitor/examples/metrics/observer.py I get the error 

`TypeError: Object of type 'Envelope' is not JSON serializable.`.

My current hack/workaround is to update this function 
`def _metric_to_envelope(
        self, metric_record: MetricRecord
    ) -> protocol.Envelope:`

in this file https://github.com/microsoft/opentelemetry-azure-monitor-python/blob/master/azure_monitor/src/azure_monitor/export/metrics/__init__.py

to return a dictionary.
`return envelope.to_dict()`.

**Comment by lzchen** [comment]
Nice. Thanks for catching this. PR [#92] will fix this issue.

**Comment by lzchen** [comment]
Fixed in [v0.3b1](https://pypi.org/project/opentelemetry-azure-monitor/)
